---
name: "Trakt"
guid: "4fe3201e-d6ae-4f2e-8917-e12bda571281"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-trakt.png"
version: "14"
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Record your watched media with Trakt"
description: >
  Record your watched media with Trakt.

category: "General"
artifacts:
  - "Trakt.dll"
changelog: |2-
  ### New features and improvements ###
  - Don't treat TVDB Id specially for episodes (#93) @SenorSmartyPants
